# My virutal Enviroment has been set up on the wiay server
executable = /data/wiay/undergrads/2324304m/VirtualEnv/bin/python3
arguments  = GW150914_GapPrior.py

# My output directories. I use a bash script to make these
output = /data/wiay/undergrads/project781/GW150914/GapPrior/out/out.txt
error  = /data/wiay/undergrads/project781/GW150914/GapPrior/error/error.txt
log    = /data/wiay/undergrads/project781/GW150914/GapPrior/log/log.txt

#The default computing power requested but can be increased
request_cpus   = 4
request_memory = 1024

queue